-- MySQL Script generated by MySQL Workbench
-- Thu Sep 14 17:46:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema osbb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema osbb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `osbb` DEFAULT CHARACTER SET utf8 ;
USE `osbb` ;

-- -----------------------------------------------------
-- Table `osbb`.`buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`flats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`flats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(5) NOT NULL,
  `level` TINYINT(1) NOT NULL,
  `square` FLOAT NOT NULL,
  `building_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flat2building_idx` (`building_id` ASC) VISIBLE,
  CONSTRAINT `fk_flat2building`
    FOREIGN KEY (`building_id`)
    REFERENCES `osbb`.`buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`members_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`members_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` ENUM('member', 'staff', 'accountant') NULL DEFAULT 'member',
  `member_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rol2member_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_rol2member`
    FOREIGN KEY (`member_id`)
    REFERENCES `osbb`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`tenants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`tenants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `auto_allow` TINYINT NULL,
  `member_id` INT NULL,
  `flat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tenants2member_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_tenant2flat_idx` (`flat_id` ASC) VISIBLE,
  CONSTRAINT `fk_tenants2member`
    FOREIGN KEY (`member_id`)
    REFERENCES `osbb`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tenant2flat`
    FOREIGN KEY (`flat_id`)
    REFERENCES `osbb`.`flats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`members_to_flats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`members_to_flats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `flat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_member2flat_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_flat2member_idx` (`flat_id` ASC) VISIBLE,
  CONSTRAINT `fk_member2flat`
    FOREIGN KEY (`member_id`)
    REFERENCES `osbb`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flat2member`
    FOREIGN KEY (`flat_id`)
    REFERENCES `osbb`.`flats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;